{{- if .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "startupers.fullname" . }}
  labels:
    {{- include "startupers.labels" . | nindent 4 }}
    {{- if .Values.metrics.podMonitor.labels }}
      {{- with .Values.metrics.podMonitor.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end }}
    {{- end }}
spec:
  jobLabel: {{ include "startupers.fullname" . }}
  podMetricsEndpoints:
    - port: http
      path: /metrics
      {{- if .Values.metrics.podMonitor.interval }}
      interval: {{ .Values.metrics.podMonitor.interval }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.metrics.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.metrics.podMonitor.honorLabels }}
      honorLabels: {{ .Values.metrics.podMonitor.honorLabels }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Values.metrics.podMonitor.namespace | quote }}
  selector:
    matchLabels:
      {{- include "startupers.selectorLabels" . | nindent 6 }}
{{- end }}
