{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
metadata:
  name: {{ include "startupers.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: {{ include "startupers.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "startupers.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
