{{- if (and (ne "" .Values.imageCredentials.username) (ne "" .Values.imageCredentials.password)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "startupers.fullname" . }}-registrykey
  annotations:
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "startupers.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
{{- if (eq "" .Values.settings.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "startupers.configSecretName" . }}
  annotations:
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "startupers.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.settings.config.server.postgres.connector | quote }}
  database-username: {{ .Values.settings.config.server.postgres.username | quote }}
  database-password: {{ .Values.settings.config.server.postgres.password | quote }}
  database-name: {{ .Values.settings.config.server.postgres.name | quote }}
  config.yaml: |
  {{- with .Values.settings.config }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ai-api-key: {{ .Values.settings.ai.apiKey | quote }}
  auth-activekid: {{ .Values.settings.auth.activeÎšid | quote }}
{{- end -}}
