vault:
  global:
    enabled: true
    serverTelemetry:
      prometheusOperator: false

  server:
    dev:
      enabled: true
      devRootToken: root

  injector:
    metrics:
      enabled: true
    # Affinity Settings for injector pods
    # This can either be a multi-line string or YAML matching the PodSpec's affinity field.
    # Commenting out or setting as empty the affinity variable, will allow
    # deployment of multiple replicas to single node services such as Minikube.
    affinity: ""
