repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      exclude: (^deployments/chart/templates)
    - id: check-json
    - id: check-added-large-files
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
    - id: hadolint-docker
  # - repo: https://github.com/dudefellah/pre-commit-openapi
  #   rev: "v0.0.1"
  #   hooks:
  #   - id: check-openapi
  # - repo: https://github.com/dnephin/pre-commit-golang
  #   rev: v0.5.0
  #   hooks:
  #   - id: go-fmt
  #   - id: go-vet
  #   - id: go-lint
  #   - id: go-imports
  #   - id: go-cyclo
  #     args: [-over=15]
  #   - id: no-go-testing
  #   - id: golangci-lint
  #   - id: go-critic
  #   - id: go-unit-tests
  #   - id: go-build
  #   - id: go-mod-tidy
  # - repo: local
  #   hooks:
  #     - id: trufflehog
  #       name: TruffleHog
  #       description: Detect secrets in your data.
  #       entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --only-verified --fail'
  #       language: system
  #       stages: ["commit", "push"]
