# Default values for startupers.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imageCredentials:
  registry: ghcr.io
  username: ""
  password: ""
  email: ""

image:
  repository: ghcr.io/dmanias/startupers
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

helpers:
  migrations:
    enabled: true
    image:
      repository: ghcr.io/dmanias/startupers-migrations
      pullPolicy: IfNotPresent
      tag: ""
    resources: {}
  toolPsql:
    enabled: true
    image:
      repository: ghcr.io/dmanias/startupers-postgres-wait
      pullPolicy: IfNotPresent
      tag: ""
    resources: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

commonAnnotations:
  reloader.stakater.com/auto: "true"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # allowPrivilegeEscalation: false
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # seccompProfile:
  #   type: RuntimeDefault

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

metrics:
  podMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: 30s
    scrapeTimeout: ""
    honorLabels: false
    labels:
      release: prometheus
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: 30s
    scrapeTimeout: ""
    honorLabels: false
    labels:
      release: prometheus
  prometheusRule:
    enabled: false
    namespace: ""
    additionalLabels:
      release: prometheus
    rules: []

rbac:
  create: false
  rules: []

networkPolicy:
  enabled: false
  metrics:
    enabled: false
    selector: {}
  ingressRules:
    enabled: false
    selector: {}
    customRules: []

settings:
  existingSecret: ""
  logLevel: debug
  debug: false
  config:
    logLevel: debug
    server:
      host: 127.0.0.1
      port: 8082
      timeout:
        server: 30
        read: 15
        write: 10
        idle: 5
      postgres:
        connector: postgresql://username:password@startupers-postgresql-primary:5432,startupers-postgresql-read:5432/startupers?sslmode=disable
        maxConnections: 4
        maxQueueTime: 1s
        minConnections: 3
        healthCheckPeriod: 10s
        maxConnIdleTime: 5s
        healthCheckTimeout: 5s
        maxConnWaitTimeout: 5s
