package aigrp

import (
	"context"
	"fmt"
	"github.com/sashabaranov/go-openai"
)

// GPT adjusted to use the go-openai package
func gpt(apiKey string, prompt string) (string, error) {
	client := openai.NewClient(apiKey)
	resp, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: openai.GPT4Turbo1106,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleUser,
					Content: prompt,
				},
			},
		},
	)

	if err != nil {
		fmt.Printf("ChatCompletion error: %v\n", err)
		return "", err // Return an empty string along with the error
	}

	// Ensure there is at least one choice and its message content is accessible before accessing it
	if len(resp.Choices) > 0 && resp.Choices[0].Message.Content != "" {
		fmt.Println(resp.Choices[0].Message.Content)
		return resp.Choices[0].Message.Content, nil
	}

	// If no choices are available or the message content is empty, return an appropriate error
	return "", fmt.Errorf("no response received from the AI")
}

func dalle(apiKey string, prompt string) (string, error) {
	// Create a new client with the provided API key
	client := openai.NewClient(apiKey)

	// Call the DALL-E API to generate an image
	resp, err := client.CreateImage(
		context.Background(),
		openai.ImageRequest{
			Prompt:         prompt,
			Size:           openai.CreateImageSize256x256,
			ResponseFormat: openai.CreateImageResponseFormatURL,
			N:              1,
			Model:          openai.CreateImageModelDallE2, // Specify the DALL-E model directly in the request
		},
	)
	if err != nil {
		fmt.Printf("Image generation error: %v\n", err)
		return "", err
	}

	// Ensure there is at least one generated image
	if len(resp.Data) > 0 {
		imageURL := resp.Data[0].URL
		fmt.Println("Generated image URL:", imageURL)
		return imageURL, nil
	}

	// If no images are generated, return an appropriate error
	return "", fmt.Errorf("no image generated by the AI")
}
